export const HAS_LOGGED_IN = 'HAS_LOGGED_IN'
export const HAS_LOGGED_OUT = 'HAS_LOGGED_OUT'
export const HAS_UPDATE_AVATAR = 'HAS_UPDATE_AVATAR'
export const FETCH_USER = 'FETCH_USER'
export const EDIT_USER = 'EDIT_USER'
export const FETCH_ASYNCSTORAGE_ID = 'FETCH_ASYNCSTORAGE_ID'

export const GET_CURRENT_LOCATION = "GET_CURRENT_LOCATION"
